import pyautogui
from time import sleep

pyautogui.press('win')
sleep(3)
pyautogui.write('bloco de notas')
sleep(7)
pyautogui.press('enter')
sleep(6)
pyautogui.write('Ola, este e um teste do PyAutoGUI!')
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.write('Estou automatizando o teclado e o mouse.')
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.write('Isso e muito util para tarefas repetitivas.')
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.write('Obrigado por assistir a este teste!')
sleep(1)
pyautogui.hotkey('ctrl', 'f4')
sleep(1)
for i in range(2):
    pyautogui.press('tab')
    sleep(1)
pyautogui.press('enter')
